# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Gabriel Elkadiki\Documents\GitHub\DSPA_Tool\qtGUI.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window_Qdialog(object):
    def setupUi(self, main_window_Qdialog):
        main_window_Qdialog.setObjectName("main_window_Qdialog")
        main_window_Qdialog.resize(1308, 1023)
        main_window_Qdialog.setSizeGripEnabled(False)
        main_window_Qdialog.setModal(False)
        self.console_QTextEdit = QtWidgets.QTextEdit(main_window_Qdialog)
        self.console_QTextEdit.setGeometry(QtCore.QRect(60, 60, 581, 931))
        self.console_QTextEdit.setReadOnly(True)
        self.console_QTextEdit.setObjectName("console_QTextEdit")
        self.layoutWidget = QtWidgets.QWidget(main_window_Qdialog)
        self.layoutWidget.setGeometry(QtCore.QRect(670, 60, 611, 461))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.compare_past_dates_QPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.compare_past_dates_QPushButton.setObjectName("compare_past_dates_QPushButton")
        self.verticalLayout.addWidget(self.compare_past_dates_QPushButton)
        self.calculate_price_delta_QPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.calculate_price_delta_QPushButton.setObjectName("calculate_price_delta_QPushButton")
        self.verticalLayout.addWidget(self.calculate_price_delta_QPushButton)
        self.monthly_maximum_delta_QPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.monthly_maximum_delta_QPushButton.setObjectName("monthly_maximum_delta_QPushButton")
        self.verticalLayout.addWidget(self.monthly_maximum_delta_QPushButton)
        self.max_delta_QPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.max_delta_QPushButton.setObjectName("max_delta_QPushButton")
        self.verticalLayout.addWidget(self.max_delta_QPushButton)
        self.reset_data_QPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.reset_data_QPushButton.setObjectName("reset_data_QPushButton")
        self.verticalLayout.addWidget(self.reset_data_QPushButton)
        self.clear_data_QPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.clear_data_QPushButton.setObjectName("clear_data_QPushButton")
        self.verticalLayout.addWidget(self.clear_data_QPushButton)
        self.layoutWidget1 = QtWidgets.QWidget(main_window_Qdialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(670, 530, 611, 133))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.start_date_dateEdit = QtWidgets.QDateEdit(self.layoutWidget1)
        self.start_date_dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1752, 9, 14), QtCore.QTime(0, 0, 0)))
        self.start_date_dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.start_date_dateEdit.setObjectName("start_date_dateEdit")
        self.verticalLayout_5.addWidget(self.start_date_dateEdit)
        self.stop_date_dateEdit = QtWidgets.QDateEdit(self.layoutWidget1)
        self.stop_date_dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.stop_date_dateEdit.setObjectName("stop_date_dateEdit")
        self.verticalLayout_5.addWidget(self.stop_date_dateEdit)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.set_today_QPushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.set_today_QPushButton.setObjectName("set_today_QPushButton")
        self.verticalLayout_3.addWidget(self.set_today_QPushButton)
        self.set_tomorrow_QPushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.set_tomorrow_QPushButton.setObjectName("set_tomorrow_QPushButton")
        self.verticalLayout_3.addWidget(self.set_tomorrow_QPushButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.console_QTextEdit.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()

        self.retranslateUi(main_window_Qdialog)
        QtCore.QMetaObject.connectSlotsByName(main_window_Qdialog)

    def retranslateUi(self, main_window_Qdialog):
        _translate = QtCore.QCoreApplication.translate
        main_window_Qdialog.setWindowTitle(_translate("main_window_Qdialog", "Stock Price Analysis"))
        self.compare_past_dates_QPushButton.setText(_translate("main_window_Qdialog", "Compare Past Dates"))
        self.calculate_price_delta_QPushButton.setText(_translate("main_window_Qdialog", "Calulate Price Delta"))
        self.monthly_maximum_delta_QPushButton.setText(_translate("main_window_Qdialog", "Monthly Maximum Delta"))
        self.max_delta_QPushButton.setText(_translate("main_window_Qdialog", "Max Delta"))
        self.reset_data_QPushButton.setText(_translate("main_window_Qdialog", "Reset Data"))
        self.clear_data_QPushButton.setText(_translate("main_window_Qdialog", "Clear"))
        self.label.setText(_translate("main_window_Qdialog", "Start Date"))
        self.label_2.setText(_translate("main_window_Qdialog", "Stop Date"))
        self.set_today_QPushButton.setText(_translate("main_window_Qdialog", "Today"))
        self.set_tomorrow_QPushButton.setText(_translate("main_window_Qdialog", "Tomorrow"))


